### PR TITLE
update vim-vimlparser

### PR DESCRIPTION
**Pull request by itchyny**
~Do not merge, this is still in progress...~

I finished the work and the tests finally pass!

### CODE REVIEW

**Comment by haya14busa** [comment]
Awesome! Thank you for your work!

Hmm.. the Travis commit integration doesn't work, but the Travis tests are still failing. (Maybe we need to migrate to GitHub Actions...) https://travis-ci.org/github/haya14busa/go-vimlparser/jobs/747912759
Can you fix the travis tests?

**Comment by haya14busa** [comment]
Also, I'm not actively maintaining this repository these days.
I sent an invitation to you as a collaborator, so please feel free to accept if you're interested in it.
We can also consider moving the repo under some organizations like vim-jp. What do you think?

**Comment by itchyny** [comment]
> Hmm.. the Travis commit integration doesn't work, but the Travis tests are still failing. (Maybe we need to migrate to GitHub Actions...) https://travis-ci.org/github/haya14busa/go-vimlparser/jobs/747912759
> Can you fix the travis tests?

Done. The Go version was old (1.8) so I updated to 1.14.

**Comment by itchyny** [comment]
> Also, I'm not actively maintaining this repository these days.
> I sent an invitation to you as a collaborator, so please feel free to accept if you're interested in it.
> We can also consider moving the repo under some organizations like vim-jp. What do you think?

Moving to vim-jp looks great, @mattn mentioned this topic on Slack. Better to include in vim-jp/vim-vimlparser or different repository? The code base is much different from js and py but maybe we can move into https://github.com/vim-jp/vim-vimlparser/tree/master/go/vimlparser and users can import the package. And running integrated tests is great because [some](https://github.com/vim-jp/vim-vimlparser/pull/178) [changes](https://github.com/vim-jp/vim-vimlparser/pull/177) has broke compiling to Go code. My concern is the vimlparser.vim in this repository is already diverted from the original due to `NODE_PARENEXPR` (https://github.com/vim-jp/vim-vimlparser/pull/71).

**Comment by haya14busa** [comment]
Thank you for your work! 🚀 

Yes! I also tried to add the Go change into the original vimlparser repo, but my concerns and problems were...

1. Backward in-compatible `NODE_PARENEXPR` change: I tried to make vital vimlparser module to add the backward-incompatible changes but I haven't completed it. Note that the main blocker at that time was just naming if I remember correctly, so it should be not difficult (I just wanted to use "VimL" Parser as module name but some vim-jp members prefer to use a different name and I lost the enthusiasm at that time. Reverting the `NODE_PARENEXPR` change is another option, but I guess we want this feature ideally?
2. Maintainance: go-vimlparser changes could hinder the development of vimlparser for vim/Python/JavaScript. I guess you may notice but go-vimlparser contains many ad-hoc code and it's not always easy to follow the original change.

I propose to move the repo to vim-jp org as a separate repo as a first step and we can work on merging the repos later.

**Pull request merged**
